apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-from-source
spec:
  inputs:
    resources:
      - name: git-source
        type: git
      - name: url
        value: https://github.com/sandeep782/deploy-app-using-tekton-on-kubernetes.git
    params:
      - name: pathToContext
        description: 'The path to the build context, used by Kaniko - within the workspace'
        default: "src"
      - name: pathToDockerfile
        description: The path to the dockerfile to build
        default: "Dockerfile"
      - name: imageUrl
        description: value should be like - us.icr.io/test_namespace/builtImageApp
        default: de.icr.io/cloud-space/app1
      - name: imageTag
        description: Tag to apply to the built image
        default: latest
  steps:
#     - name: list-src
#       image: 'alpine:3.14'
#       command:
#         - ls
#       args:
#         - $(inputs.resources.url)
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - '--context=$(inputs.resources.url)/$(inputs.params.pathToContext)/'
        - '--dockerfile=$(inputs.params.pathToDockerfile)'
        - '--destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)'
        - "--verbosity=trace"
       
